
#  FMC1 pins (J1 pins on the FMC 105 Debug boards)

#    set_property PACKAGE_PIN K20 [get_ports FMC1_LPC_LA00_CC_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA00_CC_N]
#    set_property PACKAGE_PIN K19 [get_ports FMC1_LPC_LA00_CC_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA00_CC_P]
#    set_property PACKAGE_PIN N20 [get_ports FMC1_LPC_LA01_CC_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA01_CC_N]
#    set_property PACKAGE_PIN N19 [get_ports FMC1_LPC_LA01_CC_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA01_CC_P]
#    set_property PACKAGE_PIN L22 [get_ports FMC1_LPC_LA02_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA02_N]
#    set_property PACKAGE_PIN L21 [get_ports FMC1_LPC_LA02_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA02_P]
    set_property PACKAGE_PIN K21 [get_ports FMC1_LPC_LA03_N]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA03_N]
    set_property PACKAGE_PIN J20 [get_ports FMC1_LPC_LA03_P]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA03_P]
    set_property PACKAGE_PIN M22 [get_ports FMC1_LPC_LA04_N]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA04_N]
    set_property PACKAGE_PIN M21 [get_ports FMC1_LPC_LA04_P]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA04_P]
    set_property PACKAGE_PIN N18 [get_ports FMC1_LPC_LA05_N]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA05_N]
    set_property PACKAGE_PIN N17 [get_ports FMC1_LPC_LA05_P]
    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA05_P]
#    set_property PACKAGE_PIN K18 [get_ports FMC1_LPC_LA06_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA06_N]
#    set_property PACKAGE_PIN J18 [get_ports FMC1_LPC_LA06_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA06_P]
#    set_property PACKAGE_PIN K15 [get_ports FMC1_LPC_LA07_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA07_N]
#    set_property PACKAGE_PIN J15 [get_ports FMC1_LPC_LA07_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA07_P]
#    set_property PACKAGE_PIN J22 [get_ports FMC1_LPC_LA08_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA08_N]
#    set_property PACKAGE_PIN J21 [get_ports FMC1_LPC_LA08_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA08_P]
#    #    set_property PACKAGE_PIN M16 [get_ports FMC1_LPC_LA09_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA09_N]
#    set_property PACKAGE_PIN M15 [get_ports FMC1_LPC_LA09_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA09_P]

#    set_property PACKAGE_PIN M17 [get_ports FMC1_LPC_LA10_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA10_N]
#    set_property PACKAGE_PIN L17 [get_ports FMC1_LPC_LA10_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA10_P]
#    set_property PACKAGE_PIN R21 [get_ports FMC1_LPC_LA11_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA11_N]
#    set_property PACKAGE_PIN R20 [get_ports FMC1_LPC_LA11_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA11_P]
#    set_property PACKAGE_PIN P22 [get_ports FMC1_LPC_LA12_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA12_N]
#    set_property PACKAGE_PIN N22 [get_ports FMC1_LPC_LA12_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA12_P]
#    set_property PACKAGE_PIN R16 [get_ports FMC1_LPC_LA13_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA13_N]
#    set_property PACKAGE_PIN P16 [get_ports FMC1_LPC_LA13_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA13_P]
#    set_property PACKAGE_PIN J17 [get_ports FMC1_LPC_LA14_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA14_N]
#    set_property PACKAGE_PIN J16 [get_ports FMC1_LPC_LA14_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA14_P]
#    set_property PACKAGE_PIN P21 [get_ports FMC1_LPC_LA15_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA15_N]
#    set_property PACKAGE_PIN P20 [get_ports FMC1_LPC_LA15_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA15_P]
#    set_property PACKAGE_PIN P15 [get_ports FMC1_LPC_LA16_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA16_N]
#    set_property PACKAGE_PIN N15 [get_ports FMC1_LPC_LA16_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA16_P]
#    set_property PACKAGE_PIN B20 [get_ports FMC1_LPC_LA17_CC_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA17_CC_N]
#    set_property PACKAGE_PIN B19 [get_ports FMC1_LPC_LA17_CC_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA17_CC_P]
#    set_property PACKAGE_PIN C20 [get_ports FMC1_LPC_LA18_CC_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA18_CC_N]
#    set_property PACKAGE_PIN D20 [get_ports FMC1_LPC_LA18_CC_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA18_CC_P]
#    set_property PACKAGE_PIN E20 [get_ports FMC1_LPC_LA19_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA19_N]
#    set_property PACKAGE_PIN E19 [get_ports FMC1_LPC_LA19_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA19_P]



#    FMC1 pins (J20 pins on the FMC 105 Debug boards)

set_property PACKAGE_PIN G21 [get_ports FMC1_LPC_LA20_N]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA20_N]
set_property PACKAGE_PIN G20 [get_ports FMC1_LPC_LA20_P]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA20_P]
set_property PACKAGE_PIN F22 [get_ports FMC1_LPC_LA21_N]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA21_N]
set_property PACKAGE_PIN F21 [get_ports FMC1_LPC_LA21_P]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA21_P]
set_property PACKAGE_PIN F17 [get_ports FMC1_LPC_LA22_N]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA22_N]
set_property PACKAGE_PIN G17 [get_ports FMC1_LPC_LA22_P]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA22_P]
set_property PACKAGE_PIN G16 [get_ports FMC1_LPC_LA23_N]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA23_N]
#    set_property PACKAGE_PIN G15 [get_ports FMC1_LPC_LA23_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA23_P]

#set_property PACKAGE_PIN A22 [get_ports FMC1_LPC_LA24_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA24_N]
#set_property PACKAGE_PIN A21 [get_ports FMC1_LPC_LA24_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA24_P]
#    set_property PACKAGE_PIN B15 [get_ports FMC1_LPC_LA25_N]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA25_N]
#    set_property PACKAGE_PIN C15 [get_ports FMC1_LPC_LA25_P]
#    set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA25_P]

#    set_property PACKAGE_PIN E18 [get_ports FMC1_LPC_LA26_N]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA26_N]
#    set_property PACKAGE_PIN F18 [get_ports FMC1_LPC_LA26_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA26_P]
set_property PACKAGE_PIN C18 [get_ports FMC1_LPC_LA27_N]
set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA27_N]
#    set_property PACKAGE_PIN C17 [get_ports FMC1_LPC_LA27_P]
#        set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA27_P]

#   FMC1 pins (J16 pins on the FMC 105 Debug boards)

#   set_property PACKAGE_PIN C22 [get_ports FMC1_LPC_LA28_N]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA28_N]
#   set_property PACKAGE_PIN D22 [get_ports FMC1_LPC_LA28_P]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA28_P]
#   set_property PACKAGE_PIN B17 [get_ports FMC1_LPC_LA29_N]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA29_N]
#   set_property PACKAGE_PIN B16 [get_ports FMC1_LPC_LA29_P]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA29_P]
#   set_property PACKAGE_PIN D21 [get_ports FMC1_LPC_LA30_N]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA30_N]
#   set_property PACKAGE_PIN E21 [get_ports FMC1_LPC_LA30_P]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA30_P]
#   set_property PACKAGE_PIN A17 [get_ports FMC1_LPC_LA31_N]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA31_N]
#   set_property PACKAGE_PIN A16 [get_ports FMC1_LPC_LA31_P]
#       set_property IOSTANDARD LVCMOS25 [get_ports FMC1_LPC_LA31_P]


#    LEDs_8_bit LEDS on ZC702 base board

set_property PACKAGE_PIN E15 [get_ports {LEDS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN D15 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN W17 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[2]}]
set_property PACKAGE_PIN W5 [get_ports {LEDS[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[3]}]
set_property PACKAGE_PIN V7 [get_ports {LEDS[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[4]}]
set_property PACKAGE_PIN W10 [get_ports {LEDS[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[5]}]
set_property PACKAGE_PIN P18 [get_ports {LEDS[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[6]}]
set_property PACKAGE_PIN P17 [get_ports {LEDS[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LEDS[7]}]



#    ZC702 buttons
set_property PACKAGE_PIN F19 [get_ports SW7]
set_property IOSTANDARD LVCMOS25 [get_ports SW7]
#   set_property PACKAGE_PIN B6 [get_ports {xsw_2bits_tri_i[1]}]
#       set_property IOSTANDARD LVCMOS25 [get_ports {xsw_2bits_tri_i[1]}]
#   set_property PACKAGE_PIN G19 [get_ports {SW5}]
#       set_property IOSTANDARD LVCMOS25 [get_ports {SW5}]

# GPIO DIP Switch (SW12)
#  (SW12.1)
set_property PACKAGE_PIN W7 [get_ports DIP_SW1]
set_property IOSTANDARD LVCMOS25 [get_ports DIP_SW1]

#    (SW12.2)
set_property PACKAGE_PIN W6 [get_ports DIP_SW0]
set_property IOSTANDARD LVCMOS25 [get_ports DIP_SW0]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FMC1_LPC_LA03_P_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FMC1_LPC_LA20_P_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FMC1_LPC_LA06_P_IBUF]

#    set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets n_1_n_0_FMC1_LPC_LA06_P_IBUF_inst_BUFG_inst]
#    set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets n_5_n_4_FMC1_LPC_LA03_P_IBUF_inst_BUFG_inst]
#    set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets n_3_n_2_FMC1_LPC_LA20_P_IBUF_inst_BUFG_inst]

#create_clock -name clk_w -period 200 [get_ports FMC1_LPC_LA22_P]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_src_i/CLK100]]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]

set_property port_width 34 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list NI0/valid NI0/error {NI0/counter0[0]} {NI0/counter0[1]} {NI0/counter0[2]} {NI0/counter0[3]} {NI0/counter0[4]} {NI0/counter0[5]} {NI0/counter0[6]} {NI0/counter0[7]} {NI0/counter0[8]} {NI0/counter0[9]} {NI0/counter0[10]} {NI0/counter0[11]} {NI0/counter0[12]} {NI0/counter0[13]} {NI0/counter0[14]} {NI0/counter0[15]} {NI0/counter0[16]} {NI0/counter0[17]} {NI0/counter0[18]} {NI0/counter0[19]} {NI0/counter0[20]} {NI0/counter0[21]} {NI0/counter0[22]} {NI0/counter0[23]} {NI0/counter0[24]} {NI0/counter0[25]} {NI0/counter0[26]} {NI0/counter0[27]} {NI0/counter0[28]} {NI0/counter0[29]} {NI0/counter0[30]} {NI0/counter0[31]}]]

